### ISSUE TITLE
File utPLSQL-demo-project/test/run.sql doesn't comply to new constructor of ut_coverage_sonar_reporter

### ISSUE THREAD

**Issue by jsmt** [utPLSQL/utPLSQL-demo-project#2]
Hey,

I was working through this demo, thanks by the way for all the incredible effort ! - and I couldn't get this to work on my machine because the constructor signature of the reporters has changed. 

I believe run.sql should be changed to:
...
  l_reporter := ut_coverage_sonar_reporter( );
  l_reporters.extend;
  l_reporters(l_reporters.last) := l_reporter;
  :sonar_coverage_reporter_id := l_reporter.reporter_id;

  l_reporter := ut_sonar_test_reporter( );
  l_reporters.extend;
  l_reporters(l_reporters.last) := l_reporter;
  :sonar_test_reporter_id := l_reporter.reporter_id;

  ut_runner.run(user,l_reporters, a_source_files => ut_varchar2_list(
        'source/award_bonus/award_bonus.prc',
        'source/remove_rooms_by_name/remove_rooms_by_name.prc',
        'source/between_string/betwnstr.fnc'
      ), a_test_files => ut_varchar2_list(
        'test/award_bonus/test_award_bonus.pkb',
        'test/remove_rooms_by_name/test_remove_rooms_by_name.pkb',
        'test/between_string/test_betwnstr.pkb'
      ));
...

This works fine in my tests.

Kind regards,
Jan

**Comment by jgebal** [comment]
Thanks for the info.
The project needs to be updated to work on latest release version of utplsql.
It could also use utplsql-cli to run the tests.
That would make the config much easier.
Something to work on.
Looks like I have forgot to update this project for a while

**Comment by jgebal** [comment]
I've checked. The `run.sql` script is not used anymore.
This is why it became outdated.
I will remove it, as we execute the demo project using `utplsql-sql-cli`
You may see how it's invoked [here](https://github.com/utPLSQL/utPLSQL-demo-project/blob/develop/.travis.yml#L52)

The `utplsq-sql-cli` and `utplsql-cli` projects are created to simplify the invocation of the tests from client side and CI/CD services.

**Comment by jgebal** [comment]
Removed the obscure script.
Thanks @jsmt
