### ISSUE TITLE
run.sh trouble

### ISSUE THREAD

**Issue by cruepprich** [utPLSQL/utPLSQL-demo-project#4]
When I first ran run.sh (located in the test directory), it couldn't find the test and source directories. I had to correct the paths to ../test and ../source.
Then I received this error:
`java.sql.SQLRecoverableException: IO Error: could not resolve the connect identifier  "opcdb"`

I verified that the connect identifier opcdb was correct. The only way around this error for me was to use the jdbc type connection:  host:port/sid.

The following changes made it work:

```
#!/bin/bash

set -ev

utPLSQL-cli/bin/utplsql run ${DB_USER}/${DB_PASS}@${DB_HOST}:${DB_PORT}/${ORACLE_SID} \
-source_path=../source -test_path=../test \
-f=ut_documentation_reporter  -c \
-f=ut_coverage_sonar_reporter -o=coverage.xml \
-f=ut_sonar_test_reporter     -o=test_results.xml
```

Thanks!

**Comment by jgebal** [comment]
This project was not maintained for a while and by default it is pointing to an obsolete version of `utPSLQL-cli` (beta - pre-release)
What version of utPLSQL-cli you were using?
Did you have a look at the doc in utPLSQL-cli project?

Cheers
Jacek

**Comment by jgebal** [comment]
closing as no-reply
