### ISSUE TITLE
install scripts paths

### ISSUE THREAD

**Issue by cruepprich** [utPLSQL/utPLSQL-demo-project#5]
The install.sh scripts are pointing to the wrong paths. Looks like they were thought to be one directory level up.

Cheers.

**Comment by jgebal** [comment]
All the project scripts are designed to be executed from project root folder.
It might seem counter-intuitive, but this is how it works.
If you will have a look at `travis.yml` and our [travis build](https://travis-ci.org/utPLSQL/utPLSQL-demo-project/builds/255036566), you might get a sense of how it works.

**Comment by cruepprich** [comment]
Thanks for the clarification, Jacek.
